### ISSUE TITLE
Xarray can only take datetime object for 'ns' only and not for'm'

### ISSUE THREAD

**Issue by Ashar25** [Ashar25/RainyDay#11]
The xarray object can only read time arrays as nanoseconds rather than minutes. Changing this can have severe issues in the future parts of the code.

**Comment by danielbwright** [comment]
It isn't limited to nanoseconds. Hours will also work. For some reason, however, minutes will not. So annoying.

**Comment by danielbwright** [comment]
Can we close this issue?

**Comment by Ashar25** [comment]
I hope so. If it is okay to have cattime as numpy array, we can close this.
