### ISSUE TITLE
Inconsistent typing of 'latrange' and 'lonrange'

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#15]
The following issue was detected while revising diagnostic plotting capabilities. To reproduce this, your json file likely needs "DIAGNOSTICPLOTS" : "true"

If "CREATECATALOG" : "true", latrange and lonrange are numpy arrays, whereas if "CREATECATALOG" : "false", then they are xarray data arrays. This needs to be made consistent, preferably making them xarray data arrays in both cases.

**Comment by Ashar25** [comment]
This can be fixed the only problem with xarrays here is np.where is the primary function which is not working properly with xarray. I think we can make them as xarray dataarray everywhere and then use it as a NumPy array wherever required.

**Comment by danielbwright** [comment]
THis is a high priority.

**Comment by Ashar25** [comment]
Done until the diagnostic plot but I believe it can work for FA too.
