### ISSUE TITLE
Change location of storm catalog files

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#16]
Now that we are creating a lot of files, let's change the location in which they are saved. Specifically, let's use:
"MAINPATH"/"SCENARIONAME"/"CATALOGNAME"

So, for example, the result could look like:
/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_uncorrected_nclimgrid/Madison_ExampleCatalog_nclimgrid100.nc

**Comment by Ashar25** [comment]
Yes, I was thinking to do this before pushing it here. I will do it. We can make separate folder for storm files in the mainpath or you want it in scenarioname?

**Comment by danielbwright** [comment]
This is a high priority.

**Comment by Ashar25** [comment]
Done.

**Comment by danielbwright** [comment]
Can you point me to the code for this? It doesn't seem to be behaving any different than before.

**Comment by Ashar25** [comment]
Are you able to merge my branch into yours ?   Check line 181 in my branch for this particular issue.

**Comment by danielbwright** [comment]
Never mind, I'll fix it myself. It is a very minor issue.

**Comment by Ashar25** [comment]
This is weird. I more worried about the merging part because it should have generated a separate folder for the catalogs. 
 if CreateCatalog:
    try:
        os.mkdir(wd + '/' + 'Storm_Catalog')
    except OSError as exc:
        if exc.errno != 17:   ### This checks the file exist error. '17' this is for file exist error.
            raise
        pass

This is the command I added. Let me know if these are there in the code or not.

**Comment by danielbwright** [comment]
yes, but it needed to be 'fullpath', not 'wd'. DOn't worry, I am fixing it.

**Comment by Ashar25** [comment]
ok, actually I was trying to make a separate folder for storm catalogs in the mainpath apart from scenarioname.
