### ISSUE TITLE
need to add back in ability to change durations

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#17]
We need to add in the capability currently commented out within the code block:
#==============================================================================
# If the storm catalog has a different duration than the specified duration, fix it!
# find the max rainfall for the N-hour duration, not the M-day duration
#==============================================================================

**Comment by danielbwright** [comment]
Ashar, did you already fix this? I see now that it seems like you have (lines 2000-2041).

**Comment by Ashar25** [comment]
Yes, this was done. I think we have discussed this one.  The only issue was if someone wants a lower duration storm then the actual storm catalog, say 24-hour instead of 72-hour storm; we won't be able to plot diagnostic plots for them.
