### ISSUE TITLE
unnecessary dimensions in storm catalog files?

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#19]
Do we really need all these:
netcdf file:/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/Madison_ExampleCatalog_nclimgrid84.nc {
  dimensions:
    catmax = 100;
    xloc = 100;
    yloc = 100;
    stormtime = 100;
    duration = 3;
    time = 3;
    longitude = 60;
    latitude = 36;

It seems like we could have just 4 dimensions: 'latitude', 'longitude', 'time' and something like 'nstorms'

**Comment by Ashar25** [comment]
I don't think this is unnecessary. The issue was we had added the storm variables like cat time, catmax, catx, caty as arrays to each of the storm netcdfs. The variables cannot be added without having a dimension in xarray (as far as I have understood and tried).

**Comment by Ashar25** [comment]
We can have a single dimension for catmax, xloc, yloc, and time.

**Comment by danielbwright** [comment]
this is a high priority.

**Comment by Ashar25** [comment]
Done.
