### ISSUE TITLE
When creating a new storm catalog, delete existing files

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#20]
If someone is creating a new set of storm catalog files, check first to see if those files exist and if they do, delete them. I have been encountering weird permissions problems when attempting to overwrite existing storm catalog files.

**Comment by Ashar25** [comment]
I will try to do this. I also faced this issue in mac. Although, I have never seen something like this in windows. The windows automatically replaces the existing files if they have same name. I will look trough this.

**Comment by danielbwright** [comment]
Please only delete these after the storms have been identified, rather than at the beginning of the code.

**Comment by danielbwright** [comment]
This is a high priority.

**Comment by Ashar25** [comment]
Done. Little difficult to check but I hope it is working now.

**Comment by danielbwright** [comment]
We need to reopen this, because it isn't working right. Please test on a larger set of storms (I think you said you only used 3). When the number goes beyond 9, problems will appear since the list is not correctly sorted.
