### ISSUE TITLE
Impossibly high rainfall values from frequency analysis

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#23]
When testing the Madison test case with nclimgrid-daily, I get impossibly high rainfall return periods:
![RainyDay_MadisonExample_24hr_empirical_uncorrected_nclimgrid_FrequencyAnalysis](https://github.com/Ashar25/RainyDay/assets/17144561/8ac6267c-92ae-4a3c-a37c-09dcb0b4261c)

**Comment by danielbwright** [comment]
It seems like this is working now, though I'm not clear on what change I made fixed it. We should verify a bit more before closing this issue.

**Comment by Ashar25** [comment]
Ah, maybe the -9999 values are doing this. What do you think?
