### ISSUE TITLE
stormlist not sorted

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#24]
Stormlist should be sorted from smallest catmax value to largest catmax value. Instead, the ordering appears to be random:
...
'Madison_ExampleCatalog_nclimgrid502.nc',
 'Madison_ExampleCatalog_nclimgrid55.nc',
 'Madison_ExampleCatalog_nclimgrid442.nc',
 'Madison_ExampleCatalog_nclimgrid660.nc',
 'Madison_ExampleCatalog_nclimgrid720.nc',
 'Madison_ExampleCatalog_nclimgrid631.nc',
 'Madison_ExampleCatalog_nclimgrid771.nc',
 'Madison_ExampleCatalog_nclimgrid369.nc',
 'Madison_ExampleCatalog_nclimgrid229.nc',
 'Madison_ExampleCatalog_nclimgrid338.nc',
 'Madison_ExampleCatalog_nclimgrid278.nc',
 'Madison_ExampleCatalog_nclimgrid268.nc',
 'Madison_ExampleCatalog_nclimgrid328.nc',
etc.

I believe it would be sufficient to just sort these by the storm number, without any change to the files themselves, e.g.:
'Madison_ExampleCatalog_nclimgrid1.nc',
'Madison_ExampleCatalog_nclimgrid2.nc',
'Madison_ExampleCatalog_nclimgrid3.nc',
etc.

**Comment by Ashar25** [comment]
We have talked about this. The storms are sorted as they are created are sorted after the loop based on the catmax variable.  Although, the numbering which you are seeing also depends on the folder settings. If you arrange them by name it will be alright. I think so.

**Comment by Ashar25** [comment]
We can sort it using the storm number on the files.

**Comment by danielbwright** [comment]
This is a high priority, since I can't complete the diagnostic plotting or the scenarios until this is done.

**Comment by Ashar25** [comment]
Done

**Comment by danielbwright** [comment]
This isn't working properly. I see two problems:

Problem 1: I think you need to test on a larger number of storms (I think you said yesterday that you only did it on a few storms):
stormlist
Out[54]: 
['/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest100_19800920.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest101_19910912.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest102_19730430.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest103_20140629.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting
/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest104_19851101.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest105_19980610.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest106_19830816.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest107_19690717.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest108_19640819.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest109_19840709.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest10_19720613.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest110_19691011.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest111_19541010.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest112_19540702.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest113_19550730.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest114_20130418.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest115_19590827.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest116_19940914.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest117_19880921.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest118_20000912.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest119_20100406.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest11_19760424.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest120_19900509.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest121_20050724.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest122_20200517.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest123_19870814.nc',
 '/Users/daniel/Google_Drive/RainyDay2/Summer2023_RefactorTesting/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest124_19590925.nc',
etc.

Problem 2: the deleting of files before rewriting isn't working correctly, now that you added the date to each catalog file name. You are checking specific filenames, which often don't show up as exact duplicates. For example:
 'RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest9_20000531.nc',
 '/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest9_20141013.nc'

So you have two "watershedtest9" with different dates. Then, createfilelist() is picking up those duplicates. Safer to delete all .nc files within the directory.

**Comment by Ashar25** [comment]
Dan, let me know how do you want them to be sorted?  As I can see they are sorted by their numbers (from 100-124). We have to make sure if we want to call the storms by their numbers or dates.

**Comment by danielbwright** [comment]
They need to be sorted by the "identifier number". For example, sorted by the number '118' in the following:
/RainyDay_MadisonExample_24hr_empirical_nclimgrid_watershedtest/StormCatalog/Madison_ExampleCatalog_nclimgrid_watershedtest118_20000912.nc',

If you look closely, you'll see problems with this output. I'll omit the rest of the path for clarity:
[_watershedtest100_19800920.nc',
_watershedtest101_19910912.nc',
_watershedtest102_19730430.nc',
_watershedtest103_20140629.nc',
_watershedtest104_19851101.nc',
_watershedtest105_19980610.nc',
_watershedtest106_19830816.nc',
_watershedtest107_19690717.nc',
_watershedtest108_19640819.nc',
_watershedtest109_19840709.nc',
_watershedtest10_19720613.nc',
_watershedtest110_19691011.nc',
_watershedtest111_19541010.nc',
_watershedtest112_19540702.nc',
_watershedtest113_19550730.nc',
_watershedtest114_20130418.nc',
_watershedtest115_19590827.nc',
_watershedtest116_19940914.nc',
_watershedtest117_19880921.nc',
_watershedtest118_20000912.nc',
_watershedtest119_20100406.nc',
_watershedtest11_19760424.nc',
_watershedtest120_19900509.nc',
_watershedtest121_20050724.nc',
_watershedtest122_20200517.nc',
_watershedtest123_19870814.nc',
_watershedtest124_19590925.nc',
etc.

For example, it jumps from storm 109 to storm 10 and then to storm 111.

**Comment by Ashar25** [comment]
Yeah, I can see them now.

**Comment by danielbwright** [comment]
This still isn't working fully. It seems to work correctly when CREATECATALOG is true, but not when it is false.

**Comment by Ashar25** [comment]
Dan, just forgot to edit the code in the CREATECATALOG = TRUE part of the code. If you have not made any changes yet I can just push it again

**Comment by danielbwright** [comment]
Let me push. I will do it now.

-
Daniel Wright
Associate Professor
Civil and Environmental Engineering
University of Wisconsin-Madison

________________________________

**Comment by Ashar25** [comment]
Let me know when you do it.

**Comment by danielbwright** [comment]
Ok, I pushed it. Thanks.

**Comment by Ashar25** [comment]
Added the change and pushed it again.
