### ISSUE TITLE
Problem with "INCLUDEYEARS" 

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#26]
I'm not sure how "INCLUDEYEARS" needs to be formatted in the json file. In the past, one could provide a range such as  INCLUDEYEARS 2001-2022, but now I get an error in createfilelist():
    if file_year in includeyears and file_month not in excludemonths:

TypeError: 'in <string>' requires string as left operand, not int

At the very least, I need to know how to properly format something for includeyears. Ideally, the user could  provide a range like 2001-2022 or could provide a list like 2001,2002,2008,2009.

**Comment by Ashar25** [comment]
Includeyears can take a list with square brackets around the years user wants to include. For example includeyears can be [2001,2004,2006]. All other values given will be considered as all the years are to be included in the analysis. 
For the user to give a range of years I need to do a little change. I have something in my mind.

**Comment by Ashar25** [comment]
I have made some changes to improve the way "INCLUDEYEARS" will take values from the user. User can give a range of years in the form '1990-2000' or can give 'all' for taking all the years. The user can also give a list of years to include like [2000, 2002, 2010] or the user can also give it like '2000,2002,2010'.

I would like to include these changes once you reply to this issue. I can add this change and oush it again if you haven't made any change yet since my last push.

**Comment by danielbwright** [comment]
Sounds great, thanks. You can commit these changes now-I haven’t done anything since Friday.

--
Daniel B. Wright (he/him/his)
Associate Professor, Civil and Environmental Engineering
University of Wisconsin-Madison
Hydroclimate Extremes Research Group (https://her.cee.wisc.edu/)

Visiting Scientist, Office of Water Prediction
National Oceanic and Atmospheric Administration




From: Ashar25 ***@***.***>
Date: Monday, August 21, 2023 at 4:53 PM
To: Ashar25/RainyDay ***@***.***>
Cc: Daniel Wright ***@***.***>, Author ***@***.***>
Subject: Re: [Ashar25/RainyDay] Problem with "INCLUDEYEARS" (Issue #26)

I have made some changes to improve the way "INCLUDEYEARS" will take values from the user. User can give a range of years in the form '1990-2000' or can give 'all' for taking all the years. The user can also give a list of years to include like [2000, 2002, 2010] or the user can also give it like '2000,2002,2010'.

I would like to include these changes once you reply to this issue. I can add this change and oush it again if you haven't made any change yet since my last push.

**Comment by Ashar25** [comment]
Closing the issue as completed.
