### ISSUE TITLE
Should we do something else with time units?

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#33]
Ashar, given that we discussed how xarray struggles with minutes as a unit of time, I was surprised to see that writecatalog_ash still uses times_units, times_calendar = 'minutes since 1970-01-01 00:00.0' , 'gregorian'

Should we change this? It doesn't seem to raise any problems, but I'm a bit confused as to why it doesn't.

**Comment by danielbwright** [comment]
It seems that time units are never actually written to the catalog files:
<img width="842" alt="image" src="https://github.com/Ashar25/RainyDay/assets/17144561/80f8cd13-ed1d-462c-9a1e-5dcd9d60746e">

**Comment by Ashar25** [comment]
This can be deleted. I just copied this from the last writecatalog function. This can be deleted.
