### ISSUE TITLE
Excludemonths and includeyears for the storms using storm date in the catalogname

### ISSUE THREAD

**Issue by Ashar25** [Ashar25/RainyDay#38]
We can make the exclusion of storms based on the date added to the name of the catalog file

**Comment by Ashar25** [comment]
Dan, I can do this fairly easily now. I just tried to do it. I can add this particular functionality if you don't have to make any further changes in the code.

**Comment by danielbwright** [comment]
Ashar, sounds ok, though I would also like the ability to exclude based on "storm number", e.g., using 5 to exclude Madison_ExampleCatalog_nclimgrid_watershedtest5_20040609.nc

**Comment by Ashar25** [comment]
Yes, I will do this for all three variables in the same way although, I have not added it in the current push.

**Comment by Ashar25** [comment]
Done but has not been intensely tested. We can check it as we go through and use it.
