### ISSUE TITLE
#Diagnostic plots getting cropped on the side 

### ISSUE THREAD

**Issue by Ashar25** [Ashar25/RainyDay#39]
The plots are getting cropped on the sides. I am not sure if it just for me.

**Comment by danielbwright** [comment]
I would need to see an example to understand what you mean.

**Comment by Ashar25** [comment]
![ProbabilityOfStorms](https://github.com/Ashar25/RainyDay/assets/103401328/b5445645-12f9-4ef5-a61c-d3811af11009)

If you can see the picture. I meant the text displayed or the title of the picture is not fully displayed. I tried to improve this using plt.tight_layout() but it is not working.
