### ISSUE TITLE
Dumping json file contents to netcdf outputs

### ISSUE THREAD

**Issue by danielbwright** [Ashar25/RainyDay#46]
Can we create a variable in the netcdf outputs (e.g., storm catalog files) so that contains the contents of the json file? That will improve reproducibility of an analysis.

**Comment by Ashar25** [comment]
I have saved the contents of the JSON file in the attributes section of the NetCDF file rather than as a variable. One can access the attributes using "dataset.attrs" where "dataset" is the storm catalog file variable you are using.

**Comment by danielbwright** [comment]
Perfect!

-
Daniel Wright
Associate Professor
Civil and Environmental Engineering
University of Wisconsin-Madison

________________________________
