### ISSUE TITLE
CONUS404 showing issues with "catmask" array. All other datasets working fine.

### ISSUE THREAD

**Issue by Ashar25** [Ashar25/RainyDay#5]
Please check the latest branch i.e., CREATEFILELISTV2. All the changes are made under it and it is working for all the datasets. The latest version of RainyDay is showing issues with catmask array. The dimensions of latrange lonrange are not matching with catmask.

**Comment by danielbwright** [comment]
Is this still unresolved?

**Comment by Ashar25** [comment]
I think this is done now after changing the findsubbox function. If you have tested the arrays like latrange and lonrange we can close this now.
