### ISSUE TITLE
Readnetcdf

### ISSUE THREAD

**Issue by Ashar25** [Ashar25/RainyDay#8]
The new readnetcdf can only work with dataset having dimension name similar to coordinate name or variable name. This is not working on Stage4 dataset.

**Comment by Ashar25** [comment]
Please checkout previous commits from this one to run stage4 dataset. Thanks!!!!

**Comment by danielbwright** [comment]
Can we mark this as resolved or is this problem still remaining?

**Comment by Ashar25** [comment]
Let's close this one.
